- name: Création des répertoires app/tools & app/configs -> /opt/app
  file:
    path: "/opt/app/{{ item.path }}/"
    state: directory
  with_filetree: "{{playbook_dir}}/../files/setup/app"
  when: item.state == 'directory'

- name: Copie des fichiers 'app'
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/opt/app/{{ item.path }}"
    mode: "{{ item.mode }}"
  with_filetree: "{{playbook_dir}}/../files/setup/app"
  when:
    - item.state == 'file'
    - item.path | regex_search('\.jinja2$') == none
    - item.path | basename != '.gitkeep'
    - item.path | basename != '.DS_Store'

- name: Copie des template de l'arborescence /opt/app
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/opt/app/{{ (item.path | splitext)[0] }}"
    mode: "{{ item.mode }}"
  with_filetree: "{{playbook_dir}}/../files/setup/app"
  when:
    - item.state == 'file'
    - item.path | regex_search('\.jinja2$') != none
    - item.path | basename != '.gitkeep'
    - item.path | basename != '.DS_Store'

- name: Nettoyage des permissions sudo pour le groupe 'website'
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "website"

- name: copy du fichier docker compose
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/app/docker-compose.system.yml"
  with_fileglob:
    - "{{playbook_dir}}/../files/setup/app/docker-compose.system.yml"

- name: check du docker network
  ansible.builtin.shell:
    chdir: /opt/app
    cmd: docker network ls --filter name=website -q
  register: network

- name: Root only pour tous les répertoires applicatifs
  file:
    path: "/opt/app"
    state: directory
    owner: root
    group: root
    mode: 770

- name: Install htpasswd
  apt:
    name: [apache2-utils]
